#define TAPPING_TERM 230
#define TAPPING_TERM_PER_KEY

#define MK_3_SPEED
#define MK_MOMENTARY_ACCEL
#define MK_C_OFFSET_UNMOD 8
#define MK_C_OFFSET_2 16
#define PERMISSIVE_HOLD

#define COMBO_STRICT_TIMER
#define COMBO_TERM 20
